export const occasions = [
    'Passover',
    'Thank You',
    'Get Well',
    'Make Someone Smile',
    'Love Romance',
    'New Baby',
    'Birthday',
    'Just Because',
    'Anniversary',
]

export const colors = [
    '#A859CD',
    '#E20000',
    '#FFD200',
    '#005EC8',
    '#FFFFFF',
    '#04AC63',
    '#FF8AC1',
    '#FF7800',
]

export const styles = [
    'Cheerful for Him',
    'Classic for Him',
    'Romantic for Him',
    'Modern for Her',
    'Classic for Her',
    'Sweet & Cheerful for Her',
    'Sweet & Cheerful for Kids',
    'Romantic for Her',
    'Exotic for Her',
    'Exotic for Him',
    'Elegant',
    'Exotic',
    'Fun',
    'Modern',
    'Sweet & Cheerful for Him',
    'Traditional',
]

export const flowers = [
    'Chrysanthemums',
    'Daisies',
    'Gerbera Daisies',
    'Lilies',
    'Alstroemeria',
    'Hydrangea',
    'Roses',
    'Carnations',
    'Succulents',
    'Plants',
    'Iris',
    'Sunflowers',
    'Tulips',
    'Orchids',
    'Calla Lilies',
    'Daffodils',
    'Birds of Paradise',
]
